"""Add progress tracking fields to RagIndex model

Revision ID: 2f95bf5c4860
Revises: 88b11e9767e5
Create Date: 2025-07-03 11:17:19.618209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f95bf5c4860'
down_revision = '88b11e9767e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rag_index', schema=None) as batch_op:
        batch_op.add_column(sa.Column('indexing_status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('indexing_progress', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('indexing_error_message', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rag_index', schema=None) as batch_op:
        batch_op.drop_column('indexing_error_message')
        batch_op.drop_column('indexing_progress')
        batch_op.drop_column('indexing_status')

    # ### end Alembic commands ###
