"""Add embedding model and chunking fields to RagIndex

Revision ID: 88b11e9767e5
Revises: 448e80f1b2ad
Create Date: 2025-06-14 22:11:05.351275

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '88b11e9767e5'
down_revision = '448e80f1b2ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_model_rag_index_id', 'rag_index', ['rag_index_id'], ['id'], use_alter=True)

    with op.batch_alter_table('rag_index', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chunk_size', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('chunk_overlap', sa.Integer(), nullable=False))
        batch_op.alter_column('embedding_model_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128),
               type_=sa.String(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rag_index', schema=None) as batch_op:
        batch_op.alter_column('embedding_model_name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128),
               nullable=True)
        batch_op.drop_column('chunk_overlap')
        batch_op.drop_column('chunk_size')

    with op.batch_alter_table('model', schema=None) as batch_op:
        batch_op.drop_constraint('fk_model_rag_index_id', type_='foreignkey')

    # ### end Alembic commands ###
